### ISSUE TITLE
Missing signs: ь, ѝ, /

### ISSUE THREAD

**Issue by Nestak2** [bisak/Mac-OS-Bulgarian-Phonetic-Keyboard-Layout-as-Windows-NEW#1]
Hi @bisak ,
thanks for making the keyboard public! Do you think you could implement the 3 missing signs pointed? I implemented some changes with the Ukelele program, but my Mac doesn't recognize them. I was thinking of calling ь by option_key+y and calling ѝ by option_key+j. And the symbol / is missing and its position is taken over by the question mark.
How have you edited the keyboard layout? Also used Ukelele?
Can you maybe make the modifications and post a new version of the keyboard layout? 
thanks for an answer!

**Comment by bisak** [comment]
Hey,

I don't remember exactly because I started using the Phonetic-traditional layout. Feel free to fork the repo and try to fix these issues. I am by no means some expert on Ukelele, just watched some youtube tutorials on how to use it. I recall it took a looong time to get it as I wanted because Ukelele is very touchy.

**Comment by Nestak2** [comment]
Thanks for the answer, bisak!
Actually, by now I managed to implement the changes I wanted (it turned out I needed to restart my Mac for the changes to take place). If you are interested, I can contribute my version with the 3 changes of the keyboard to your repo, for other people that might find it useful. I am new to github, but I will read how to do this. Are you interested?

**Comment by bisak** [comment]
Fork the repo and contribute there :)

**Comment by Nestak2** [comment]
I submitted a pull request, happy to be accepted or to read what comments you have on it!
