### ISSUE TITLE
Missing letters ь & ѝ

### ISSUE THREAD

**Issue by ydm** [bisak/Mac-OS-Bulgarian-Phonetic-Keyboard-Layout-as-Windows-NEW#4]

**Comment by Atom3** [comment]
Към 23.01.2024 буквите ь и ѝ все още липсват. Има ли алтернатива на този проект в който ги има?

**Comment by borisdelev** [comment]
> Към 23.01.2024 буквите ь и ѝ все още липсват. Има ли алтернатива на този проект в който ги има?

https://github.com/jordanilchev/osx-new-phonetic гледам ей туй... ще го изтествам.

**Comment by bisak** [comment]
> > Към 23.01.2024 буквите ь и ѝ все още липсват. Има ли алтернатива на този проект в който ги има?
> 
> https://github.com/jordanilchev/osx-new-phonetic гледам ей туй... ще го изтествам.

@borisdelev 
Тотално съм занемарил това репо, понеже започнах да използвам вградения layout. Дайте обратна връзка как е подредбата от https://github.com/jordanilchev/osx-new-phonetic

**Comment by borisdelev** [comment]
> > > Към 23.01.2024 буквите ь и ѝ все още липсват. Има ли алтернатива на този проект в който ги има?
> > 
> > 
> > https://github.com/jordanilchev/osx-new-phonetic гледам ей туй... ще го изтествам.
> 
> @borisdelev Тотално съм занемарил това репо, понеже започнах да използвам вградения layout. Дайте обратна връзка как е подредбата от https://github.com/jordanilchev/osx-new-phonetic

Дам... в туй репо заработиха и Ю, ь, ѝ. :)

**Comment by bisak** [comment]
Супер, благодарско. Слагам линк в readme-то, че да не си губят време хората тук.
